# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
project_name: poc-fury-application-status-page
builds:
  - binary: 'poc-fury-application-status-page'
    id: poc-fury-application-status-page-linux
    goarch:
      - amd64
    goos:
      - linux
archives:
  - format: binary
    id: poc-fury-application-status-page-linux-bin
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - poc-fury-application-status-page-linux
checksum:
  name_template: 'sha256sum.txt'
snapshot:
  name_template: '{{ .Tag }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  ids:
    - poc-fury-application-status-page-linux-bin
  github:
    owner: sighupio
    name: poc-fury-application-status-page
  name_template: '{{ .Tag }}'
