apiVersion: v1
kind: Service
metadata:
  labels:
    app: fury-application-status-mocked
  name: fury-application-status-mocked
  namespace: fury-application-status
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app: fury-application-status-mocked